"""
Django settings for my_messageboard project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r5f_ql8-g5g*s-sh$h!8@-byxnz(k2u=(jzh80e0#f+%4f#2$!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'board',
    'captcha', # 增加驗證碼功能
]

# 配置驗證碼（可選，可自定義）
CAPTCHA_IMAGE_SIZE = (120, 50)
CAPTCHA_FONT_SIZE = 22
CAPTCHA_LENGTH = 4

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'my_messageboard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [],
        # 'DIRS': [os.path.join(BASE_DIR, 'templates')], # 增加這一行
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # 確保這一行是正確的，指向項目根目錄下的 'templates' 文件夾
        'APP_DIRS': True, # 確保這一行是 True，這樣 Django 才會自動尋找各個應用内部的 'templates' 文件夾        
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_messageboard.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db_init_v1.sqlite3', # Updated database filename
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# my_messageboard/settings.py
# Email configuration
# 默認使用控制台後端進行測試，避免在沒有配置 SMTP 的情況下出錯
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# 實際 SMTP 配置 (如果需要發送真實郵件，請取消註釋並填寫)
# EMAIL_HOST = 'smtp.gmail.com' # 例如：Gmail
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER') # 強烈建議使用環境變量
# EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD') # 強烈建議使用環境變量
# DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'webmaster@localhost') # 默認發件人

# 管理員郵箱配置，用於接收 mail_admins() 的郵件
ADMINS = [('Admin', os.environ.get('ADMIN_EMAIL'))] if os.environ.get('ADMIN_EMAIL') else []
MANAGERS = ADMINS

# 注意：在生產環境中，請務必使用環境變量或其他安全方式存儲敏感信息如郵箱密碼。
# 如果使用Gmail，可能需要開啟“允許安全性較低的應用”或生成應用專用密碼。

LOGIN_REDIRECT_URL = '/' # 登入成功後重定向到網站首頁 (留言列表頁)
LOGOUT_REDIRECT_URL = '/' # 登出成功後重定向到網站首頁
